# Generated by Django 4.2.7 on 2024-03-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_contributions_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributions',
            name='user',
        ),
        migrations.AddField(
            model_name='contributions',
            name='user',
            field=models.ManyToManyField(to='home.userprofile'),
        ),
    ]
