# Generated by Django 4.2.7 on 2024-03-05 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_userprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributions',
            name='status',
        ),
        migrations.RemoveField(
            model_name='contributionfiles',
            name='contribution',
        ),
        migrations.AlterField(
            model_name='contributions',
            name='term',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AddField(
            model_name='contributionfiles',
            name='contribution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='home.contributions'),
        ),
    ]
