# Generated by Django 4.2.7 on 2024-03-07 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closure', models.DateTimeField()),
                ('finalClosure', models.DateTimeField()),
            ],
        ),
    ]
